### ISSUE TITLE
Is this working now?

### ISSUE THREAD

**Issue by tyeeman** [jamesslinger/Amazon-Price-Checker#1]
Looking to try this? Is it easy to use my own email instead of google?

**Comment by jamesslinger** [comment]
Hey, sorry for the late reply. I've been mostly away from my computer / Github as I've had a baby so had to take time out from everything!

Yes you can use any email you want just as long as you have the correct SMTP settings for your provider. If not, I'm sure you will be able to google search how to setup your email provider to work with Python scripts.

Good luck.
